### ISSUE TITLE
out of memory when joining (NULL match?)

### ISSUE THREAD

**Issue by VladimirAlexiev** [shenwei356/csvtk#163]
I'm trying to join two files by a single field:
- entities.csv has 202740 rows, of which 3183 have `BIC`
- WD-LEI-BIC.csv has 29022 rows, of which 2073 have `bic`

This chugs along for 2-3 minutes, then fails with out of memory exception.

I have a hunch that `csvtk join` happily matches two **empty** fields and so tries to make a Cartesian product of 199k * 27k rows? That's wrong: a NULL field should not match anything, including another NULL.

```
$ csvtk join -f "BIC;bic" entities.csv WD-LEI-BIC.csv|wc -l

runtime: VirtualAlloc of 8192 bytes failed with errno=1455
fatal error: out of memory

runtime stack:
runtime.throw(0x16a8e19, 0xd)
        /usr/local/go/src/runtime/panic.go:1112 +0x79
runtime.sysUsed(0xc56a928000, 0x2000)
        /usr/local/go/src/runtime/mem_windows.go:83 +0x22e
runtime.(*mheap).allocSpan(0x1dd1240, 0x1, 0x3e00, 0x20c859410f0)
        /usr/local/go/src/runtime/mheap.go:1271 +0x3b1
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:910 +0x5f
runtime.systemstack(0x0)
        /usr/local/go/src/runtime/asm_amd64.s:375 +0x6b
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1183

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:335 fp=0xc0003eb330 sp=0xc0003eb328 pc=0xefbac0
runtime.(*mheap).alloc(0x1dd1240, 0x1, 0xec013e, 0x1de4590)
        /usr/local/go/src/runtime/mheap.go:904 +0x88 fp=0xc0003eb380 sp=0xc0003eb330 pc=0xeb9348
runtime.(*mcentral).grow(0x1de44f0, 0x0)
        /usr/local/go/src/runtime/mcentral.go:232 +0x88 fp=0xc0003eb3c8 sp=0xc0003eb380 pc=0xea9f88
runtime.(*mcentral).cacheSpan(0x1de44f0, 0x20c85941178)
        /usr/local/go/src/runtime/mcentral.go:158 +0x31f fp=0xc0003eb420 sp=0xc0003eb3c8 pc=0xea9d5f
runtime.(*mcache).refill(0x20c21630108, 0x3e)
        /usr/local/go/src/runtime/mcache.go:162 +0xbd fp=0xc0003eb468 sp=0xc0003eb420 pc=0xea921d
runtime.(*mcache).nextFree(0x20c21630108, 0xc0003eb53e, 0xe9e5a9, 0xc56a9268c0, 0x1c0)
        /usr/local/go/src/runtime/malloc.go:882 +0xa5 fp=0xc0003eb4a0 sp=0xc0003eb468 pc=0xe9e065
runtime.mallocgc(0x380, 0x15d06a0, 0xede501, 0xc56a9268c0)
        /usr/local/go/src/runtime/malloc.go:1069 +0x890 fp=0xc0003eb528 sp=0xc0003eb4a0 pc=0xe9eab0
runtime.growslice(0x15d06a0, 0xc56a9268c0, 0x1c, 0x1c, 0x1d, 0xc56a925c00, 0x1c, 0x38)
        /usr/local/go/src/runtime/slice.go:230 +0x209 fp=0xc0003eb590 sp=0xc0003eb528 pc=0xede909
github.com/shenwei356/csvtk/csvtk/cmd.glob..func25(0x1daafc0, 0xc000298340, 0x2, 0x4)
        /home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/csvtk/csvtk/cmd/join.go:245 +0x1959 fp=0xc0003ebd78 sp=0xc0003eb590 pc=0x1549eb9
github.com/spf13/cobra.(*Command).execute(0x1daafc0, 0xc000298300, 0x4, 0x4, 0x1daafc0, 0xc000298300)
        /home/shenwei/shenwei/scripts/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2 fp=0xc0003ebe38 sp=0xc0003ebd78 pc=0x11c3762
github.com/spf13/cobra.(*Command).ExecuteC(0x1dacf40, 0x1db8100, 0x0, 0xc000045f78)
        /home/shenwei/shenwei/scripts/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375 fp=0xc0003ebf18 sp=0xc0003ebe38 pc=0x11c4495
github.com/spf13/cobra.(*Command).Execute(...)
        /home/shenwei/shenwei/scripts/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/shenwei356/csvtk/csvtk/cmd.Execute()
        /home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/csvtk/csvtk/cmd/root.go:71 +0x38 fp=0xc0003ebf78 sp=0xc0003ebf18 pc=0x151f3d8
main.main()
        /home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/csvtk/csvtk/main.go:54 +0x27 fp=0xc0003ebf88 sp=0xc0003ebf78 pc=0x157a1a7
runtime.main()
        /usr/local/go/src/runtime/proc.go:225 +0x256 fp=0xc0003ebfe0 sp=0xc0003ebf88 pc=0xecc436
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1367 +0x1 fp=0xc0003ebfe8 sp=0xc0003ebfe0 pc=0xefd961
0
```

**Comment by shenwei356** [comment]
`csvtk` [reads whole files into memory](https://github.com/shenwei356/csvtk/blob/master/csvtk/cmd/join.go#L144) and matches them :(

How big are these two files? I mean file size.

**Comment by VladimirAlexiev** [comment]
29Mb and 3.1Mb

**Comment by VladimirAlexiev** [comment]
The problem is as I guessed: `csvtk join` matches two NULLs but must not:
```
$ cat a.csv
key,data1
,foo
$ cat b.csv
key,data2
,bar
$ csvtk join -f 1 a.csv b.csv
key,data1,data2
,foo,bar
```

**Comment by shenwei356** [comment]
I see. While I find that [dplyr](https://dplyr.tidyverse.org/reference/join.html) matches NULLs as `csvtk join` does.

```
$ cat a.csv 
key,data1
a,1
,foo
,100

$ cat b.csv 
key,data2
,bar
,200
a,2

# R
> left_join(a, b)
Joining, by = "key"
# A tibble: 5 x 3
  key   data1 data2
  <chr> <chr> <chr>
1 a     1     2    
2 NA    foo   bar  
3 NA    foo   200  
4 NA    100   bar  
5 NA    100   200

> full_join(a, b)
Joining, by = "key"
# A tibble: 5 x 3
  key   data1 data2
  <chr> <chr> <chr>
1 a     1     2    
2 NA    foo   bar  
3 NA    foo   200  
4 NA    100   bar  
5 NA    100   200

$ csvtk join a.csv b.csv
$ csvtk join a.csv b.csv | csvtk pretty 
key   data1   data2
---   -----   -----
a     1       2
      foo     bar
      foo     200
      100     bar
      100     20
```

But I add a new flag to skip those rows.

```
csvtk join a.csv b.csv -- ignore-null 
key,data1,data2
a,1,2

```

- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/7082590/csvtk_darwin_amd64.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/7082591/csvtk_linux_amd64.tar.gz)

**Comment by VladimirAlexiev** [comment]
Thanks! I'm on Windows so will wait for the release

**Comment by shenwei356** [comment]
Oh, sorry. 
- [csvtk_windows_amd64.exe.tar.gz](https://github.com/shenwei356/csvtk/files/7083420/csvtk_windows_amd64.exe.tar.gz)

**Comment by VladimirAlexiev** [comment]
The results are correct and it takes 3-4s:
```
$ time csvtk join --ignore-null -l -f "BIC;bic" entities.csv WD-LEI-BIC.csv | wc -l
294
real    0m3.831s
user    0m0.045s
sys     0m0.170s

$ time csvtk join --ignore-null -l -f "LEI;lei" entities.csv WD-LEI-BIC.csv | wc -l
1723
real    0m4.398s
user    0m0.062s
sys     0m0.155s
```
