### ISSUE TITLE
sort:N (natsort) error "index out of range"

### ISSUE THREAD

**Issue by VladimirAlexiev** [shenwei356/csvtk#70]
```
csvtk version
csvtk v0.17.0

csvtk sort   -tTk 5:N,4:N,3:N,1:N a.tsv

panic: runtime error: index out of range

goroutine 1 [running]:
github.com/shenwei356/natsort.Compare(0xc0001d2b9a, 0x3, 0x0, 0x0, 0x180d00, 0x0)
        /home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/natsort/natsort.go:53 +0x33a
github.com/shenwei356/util/stringutil.MultiKeyStringSliceList.Less(0xc00025e000, 0x190, 0x190, 0xc8, 0x96, 0x0)
        /home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/util/stringutil/multiKeySort.go:40 +0x19d
sort.medianOfThree(0xccee80, 0xc00021c0a0, 0xc8, 0x96, 0xfa)
        /usr/local/go/src/sort/sort.go:76 +0x50
sort.doPivot(0xccee80, 0xc00021c0a0, 0x0, 0x190, 0x729f95, 0xc00025e000)
        /usr/local/go/src/sort/sort.go:102 +0x615
sort.quickSort(0xccee80, 0xc00021c0a0, 0x0, 0x190, 0x12)
        /usr/local/go/src/sort/sort.go:190 +0xa1
sort.Sort(0xccee80, 0xc00021c0a0)
        /usr/local/go/src/sort/sort.go:218 +0x80
github.com/shenwei356/csvtk/csvtk/cmd.glob..func30(0x135aa00, 0xc0001ea340, 0x0, 0x2)
        /home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/csvtk/csvtk/cmd/sort.go:187 +0xe26
github.com/spf13/cobra.(*Command).execute(0x135aa00, 0xc0001ea300, 0x2, 0x2, 0x135aa00, 0xc0001ea300)
        /home/shenwei/shenwei/scripts/go/src/github.com/spf13/cobra/command.go:766 +0x2d3
github.com/spf13/cobra.(*Command).ExecuteC(0x135a540, 0xc0001e2380, 0xcc97c0, 0xcc9100)
        /home/shenwei/shenwei/scripts/go/src/github.com/spf13/cobra/command.go:852 +0x304
github.com/spf13/cobra.(*Command).Execute(0x135a540, 0x405527, 0xc000052058)
        /home/shenwei/shenwei/scripts/go/src/github.com/spf13/cobra/command.go:800 +0x32
github.com/shenwei356/csvtk/csvtk/cmd.Execute()
        /home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/csvtk/csvtk/cmd/root.go:67 +0x34
main.main()
        /home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/csvtk/csvtk/main.go:52 +0x27
```
[a.zip](https://github.com/shenwei356/csvtk/files/3094889/a.zip)

**Comment by VladimirAlexiev** [comment]
Similar error with a simpler file:
```
csvtk sort   -tTk 3:N,1:N c.tsv
goroutine 1 [running]:
github.com/shenwei356/natsort.Compare(0xc0001bcced, 0x1, 0xc0001bcba7, 0x0, 0x0, 0x440600)
        /home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/natsort/natsort.go:53 +0x33a
github.com/shenwei356/util/stringutil.MultiKeyStringSliceList.Less(0xc000240000, 0x190, 0x190, 0x0, 0x1, 0x0)
        /home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/util/stringutil/multiKeySort.go:40 +0x19d
sort.doPivot(0xccee80, 0xc0002272c0, 0x0, 0x190, 0x729f95, 0xc000240000)
        /usr/local/go/src/sort/sort.go:121 +0x150
sort.quickSort(0xccee80, 0xc0002272c0, 0x0, 0x190, 0x12)
        /usr/local/go/src/sort/sort.go:190 +0xa1
sort.Sort(0xccee80, 0xc0002272c0)
        /usr/local/go/src/sort/sort.go:218 +0x80
github.com/shenwei356/csvtk/csvtk/cmd.glob..func30(0x135aa00, 0xc0001dc030, 0x1, 0x3)
        /home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/csvtk/csvtk/cmd/sort.go:187 +0xe26
github.com/spf13/cobra.(*Command).execute(0x135aa00, 0xc000195f80, 0x3, 0x3, 0x135aa00, 0xc000195f80)
        /home/shenwei/shenwei/scripts/go/src/github.com/spf13/cobra/command.go:766 +0x2d3
github.com/spf13/cobra.(*Command).ExecuteC(0x135a540, 0xc0001ca3c0, 0xcc97c0, 0xcc9100)
        /home/shenwei/shenwei/scripts/go/src/github.com/spf13/cobra/command.go:852 +0x304
github.com/spf13/cobra.(*Command).Execute(0x135a540, 0x405527, 0xc0000280b8)
        /home/shenwei/shenwei/scripts/go/src/github.com/spf13/cobra/command.go:800 +0x32
github.com/shenwei356/csvtk/csvtk/cmd.Execute()
        /home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/csvtk/csvtk/cmd/root.go:67 +0x34
main.main()
        /home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/csvtk/csvtk/main.go:52 +0x27

csvtk uniq -tTf 1,2,3 c.tsv | csvtk sort   -tTk 3:N,1:N
country_code    country_name    continent_code
805     USA     6
805
```

`uniq` doesn't change values, it just reduces rows. So how can `sort` fail on the full file but succeed on the reduced file?
[c.zip](https://github.com/shenwei356/csvtk/files/3095081/c.zip)

**Comment by shenwei356** [comment]
Looks like a bug of github.com/shenwei356/natsort/, which failed to handle empty  keys.

**Comment by shenwei356** [comment]
Fixed. Please try:

- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/3095250/csvtk_linux_amd64.tar.gz)
- [csvtk_windows_amd64.exe.tar.gz](https://github.com/shenwei356/csvtk/files/3095251/csvtk_windows_amd64.exe.tar.gz)
- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/3095249/csvtk_darwin_amd64.tar.gz)

You can also switch global option `-E/--ignore-empty-row` for a.txt which contains rows without anything.

**Comment by VladimirAlexiev** [comment]
works!
